// Writes i18n/print-strings.md: the words the PRINTED book contains, found in the print code, and where each lives (file and the function or
// table that holds it). It is the plan for slice I3 ("printed pages in a language"), nothing here changes the print pipeline.
//   node i18n/print-report.mjs           rewrite i18n/print-strings.md
// test-i18n.mjs fails when the file is out of date, so a printed word added later shows up in the diff of the pull request that adds it.
// Best effort: a heuristic finds capitalised words and phrases in string literals and in the text between tags of template literals; it
// misses a word built from pieces and lists some that are not printed (the file says which section is which).
import fs from 'node:fs';
import { lex } from './lex.mjs';

const root = new URL('../', import.meta.url);
export const SECTIONS = [
  ['The pages of the book', ['pages.mjs', 'render.mjs', 'cover.mjs', 'handoff.mjs', 'keeper.mjs', 'planview.mjs', 'context.mjs']],
  ['The day page and its blocks (the editor\'s tables in daypage.mjs, TYPES and the like, are editor words: they are in the catalog already)', ['daypage.mjs']],
  ['Scan zones, accessibility print options, puzzle pages', ['scan.mjs', 'a11yprint.mjs', 'puzzles/render.mjs', 'puzzles/samples.mjs', 'puzzles/crossword.mjs', 'puzzles/wordsearch.mjs']],
  ['Content tables: facts, holidays, rulings, year text', ['facts.mjs', 'holidays.mjs', 'pioneers.mjs', 'rulings.mjs', 'japanese.mjs', 'payperiods.mjs', 'content/year.mjs', 'content/year-research.mjs']],
];

const clean = (s) => s.replace(/<[^>]*>/g, ' ').replace(/&#?\w+;/g, ' ').replace(/\$\{[^}]*\}/g, ' ').replace(/\s+/g, ' ').trim();
function printed(raw) {
  const t = clean(raw);
  if (t.length < 2 || !/[A-Za-z]{2}/.test(t)) return null;
  if (/^[#.\[(@:\/]/.test(t) || /[{};=]|:\/\//.test(t) || /^[a-z]+[A-Z]\w*$/.test(t)) return null;
  const capital = /[A-Z]/.test(t) && /[a-z]{2}/.test(t), words = t.split(' ').length;
  if (!capital && words < 3) return null; // class names, keys and ids are lower case and short
  if (!capital && !/ [a-z]{3,} /.test(' ' + t + ' ')) return null;
  return t.length > 160 ? t.slice(0, 157) + '...' : t;
}
function fromFile(src) {
  const out = []; // [function, text]
  const toks = [];
  (function all(s, base) { for (const t of lex(s)) { toks.push({ ...t, start: t.start + base }); if (t.k === 'tpl') for (const p of t.parts) if (p.e !== undefined) all(p.e, base + p.at); } })(src, 0);
  // the top-level declaration each string sits in: tokens come in source order for the outer level; nested template tokens follow their template
  const top = lex(src); let depth = 0, cur = '(top of the file)'; const at = [];
  for (let i = 0; i < top.length; i++) {
    const t = top[i];
    if (t.k === 'p' && t.v === '{') depth++; else if (t.k === 'p' && t.v === '}') depth = Math.max(0, depth - 1);
    else if (depth === 0 && t.k === 'id' && t.v === 'function' && top[i + 1] && top[i + 1].k === 'id') { cur = top[i + 1].v; at.push([t.start, cur]); }
    else if (depth === 0 && t.k === 'id' && (t.v === 'const' || t.v === 'let' || t.v === 'var') && top[i + 1] && top[i + 1].k === 'id') { cur = top[i + 1].v; at.push([t.start, cur]); }
  }
  const where = (p) => { let c = '(top of the file)'; for (const [s, n] of at) if (s <= p) c = n; else break; return c; };
  for (const t of toks) {
    if (t.k === 'str') { const p = printed(t.v); if (p) out.push([where(t.start), p]); }
    else if (t.k === 'tpl') for (const part of t.parts) if (part.s !== undefined) { for (const piece of part.s.split(/<[^>]*>/)) { const p = printed(piece); if (p) out.push([where(t.start), p]); } }
  }
  return out;
}
export function printReport() {
  let md = '# Printed strings: where each lives\n\n'
    + 'Generated by `node i18n/print-report.mjs` (BUILD-PLAN section 18, slice I1). **Nothing here is translated yet, and the print pipeline is unchanged**: this is the plan for slice I3,\n'
    + 'which moves these words into catalogs with a `book.language` setting. `test-i18n.mjs` fails when this file is out of date.\n\n'
    + 'How to read it: one block per file, then the function (or table) that holds the words, then the words. A heuristic found them (capitalised words and phrases in string\n'
    + 'literals and between tags), so a few are not printed and a word built from pieces is missed. Not listed: the support, trans and clinic packs (`packs/`), which are written in the\n'
    + 'pack\'s own language and never translated without a verified pack, scan codes and page ids (ASCII only), and the editor\'s words (`i18n/en.json`).\n';
  let total = 0, nfiles = 0;
  for (const [title, files] of SECTIONS) {
    md += `\n## ${title}\n`;
    for (const f of files) {
      const p = new URL(f, root);
      if (!fs.existsSync(p)) continue;
      const by = new Map();
      for (const [fn, s] of fromFile(fs.readFileSync(p, 'utf8'))) { if (!by.has(fn)) by.set(fn, []); if (!by.get(fn).includes(s)) by.get(fn).push(s); }
      const n = [...by.values()].reduce((a, l) => a + l.length, 0); total += n;
      if (!n) continue;
      nfiles++;
      md += `\n### \`journal/${f}\` (${n})\n`;
      for (const [fn, list] of by) md += `\n- \`${fn}\`: ${list.map((s) => '`' + s.replace(/`/g, "'") + '`').join(' · ')}\n`;
    }
  }
  return md.replace('\n## The pages', `\n**${total} strings in ${nfiles} files.**\n\n## The pages`);
}
if (process.argv[1] && new URL(import.meta.url).pathname === fs.realpathSync(process.argv[1])) {
  const out = new URL('./print-strings.md', import.meta.url), md = printReport();
  fs.writeFileSync(out, md); console.log('i18n/print-strings.md:', md.split('\n').length, 'lines');
}
