#!/usr/bin/env python3
"""Generate the large-text font set for the Keeping Watch X4 firmware (Menu, Settings, Text size: Large).

Output: src/gen/assets_large.cpp and .h. Everything is Inter (tools/Inter-*.ttf) plus DejaVu for the astro glyphs and
the small play arrows, so it builds without the Lora files that gen_assets.py needs. Sizes are about 1.3x the normal set:
23 / 28 px for captions and rows (the normal set is 17 / 21 / 22), 42 px titles, 52 px big numbers.
Same rasterizing as gen_assets.py (threshold at 50%), so the host preview is pixel-identical to the panel.
The arrows U+2192 / U+2190 are not in Inter: Canvas draws them as icons (A11Y-51), so they are left out here.
"""
import os
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'src', 'gen', 'assets_large.cpp')
HDR = os.path.join(HERE, '..', 'src', 'gen', 'assets_large.h')
DEJAVU = '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'

TEXT = ''.join(chr(c) for c in range(32, 127)) + '°–—·…’‘“”•×−é'
GLYPHS = '☉☽☿♀♂♃♄♅♆♇♈♉♊♋♌♍♎♏♐♑♒♓℞☀★✓◀▶'

FONTS = [
    ('FL_UI_S', f'{HERE}/Inter-500.ttf', 23, TEXT),      # captions, hint labels
    ('FL_UI', f'{HERE}/Inter-500.ttf', 28, TEXT),        # list rows, buttons, reading text
    ('FL_UI_B', f'{HERE}/Inter-700.ttf', 28, TEXT),      # emphasis
    ('FL_UI_XL', f'{HERE}/Inter-700.ttf', 52, TEXT),     # big numbers
    ('FL_TITLE', f'{HERE}/Inter-700.ttf', 42, TEXT),     # screen titles
    ('FL_SYM', DEJAVU, 26, GLYPHS),
]


def render_font(path, size, chars):
    f = ImageFont.truetype(path, size)
    asc, desc = f.getmetrics()
    glyphs, blob = [], bytearray()
    for ch in sorted(set(chars), key=ord):
        try:
            box = f.getbbox(ch)
        except Exception:
            continue
        adv = round(f.getlength(ch))
        x0, y0, x1, y1 = box
        w, h = max(0, x1 - x0), max(0, y1 - y0)
        off = len(blob)
        if w and h:
            im = Image.new('L', (w, h), 0)
            ImageDraw.Draw(im).text((-x0, -y0), ch, font=f, fill=255)
            bw = (w + 7) // 8
            for yy in range(h):
                row = bytearray(bw)
                for xx in range(w):
                    if im.getpixel((xx, yy)) >= 128:
                        row[xx >> 3] |= 0x80 >> (xx & 7)
                blob += row
        glyphs.append((ord(ch), off, w, h, adv, x0, y0 - asc))
    return asc, desc, glyphs, blob


def carr(name, data):
    body = ',\n'.join('  ' + ','.join(f'0x{b:02x}' for b in data[i:i + 24]) for i in range(0, len(data), 24))
    return f'static const uint8_t {name}[] = {{\n{body or "  0"}\n}};\n'


lines = ['// GENERATED by tools/gen_large.py — do not edit.', '#include "assets_large.h"', '']
hdr = ['// GENERATED by tools/gen_large.py — do not edit.', '#pragma once', '#include "../core/font.h"', '']
total = 0
for name, path, size, chars in FONTS:
    asc, desc, glyphs, blob = render_font(path, size, chars)
    total += len(blob)
    lines.append(carr(f'{name}_bits', blob))
    g = ',\n'.join(f'  {{0x{cp:04x},{off},{w},{h},{adv},{xo},{yo}}}' for cp, off, w, h, adv, xo, yo in glyphs)
    lines.append(f'static const Glyph {name}_glyphs[] = {{\n{g}\n}};')
    lines.append(f'const Font {name} = {{{name}_bits, {name}_glyphs, {len(glyphs)}, {asc}, {desc}, {asc + desc}}};\n')
    hdr.append(f'extern const Font {name};')
open(OUT, 'w').write('\n'.join(lines) + '\n')
open(HDR, 'w').write('\n'.join(hdr) + '\n')
print('wrote', OUT, f'({total} bytes of glyph bitmaps, about {total // 1024} KB of flash)')
