// Japanese calendar layer: weekday kanji (planetary week), 24 solar terms (sekki), 72 micro-seasons (kō).
// Sekki/kō boundaries are defined by the sun's apparent ecliptic longitude, so they are computed, not looked up.

export const WEEKDAYS = [
  // JS getDay(): 0 = Sunday
  { kanji: '日', kana: 'にち', romaji: 'nichi', element: 'Sun', glyph: '☉' },
  { kanji: '月', kana: 'げつ', romaji: 'getsu', element: 'Moon', glyph: '☽' },
  { kanji: '火', kana: 'か', romaji: 'ka', element: 'Fire · Mars', glyph: '♂' },
  { kanji: '水', kana: 'すい', romaji: 'sui', element: 'Water · Mercury', glyph: '☿' },
  { kanji: '木', kana: 'もく', romaji: 'moku', element: 'Wood · Jupiter', glyph: '♃' },
  { kanji: '金', kana: 'きん', romaji: 'kin', element: 'Metal · Venus', glyph: '♀' },
  { kanji: '土', kana: 'ど', romaji: 'do', element: 'Earth · Saturn', glyph: '♄' },
];

// 24 sekki, starting at 立春 (sun longitude 315°), every 15°.
export const SEKKI = [
  ['立春', 'りっしゅん', 'Risshun', 'Start of spring'],
  ['雨水', 'うすい', 'Usui', 'Rainwater'],
  ['啓蟄', 'けいちつ', 'Keichitsu', 'Insects awaken'],
  ['春分', 'しゅんぶん', 'Shunbun', 'Spring equinox'],
  ['清明', 'せいめい', 'Seimei', 'Pure and clear'],
  ['穀雨', 'こくう', 'Kokuu', 'Grain rains'],
  ['立夏', 'りっか', 'Rikka', 'Start of summer'],
  ['小満', 'しょうまん', 'Shōman', 'Lesser ripening'],
  ['芒種', 'ぼうしゅ', 'Bōshu', 'Grain beards and seeds'],
  ['夏至', 'げし', 'Geshi', 'Summer solstice'],
  ['小暑', 'しょうしょ', 'Shōsho', 'Lesser heat'],
  ['大暑', 'たいしょ', 'Taisho', 'Greater heat'],
  ['立秋', 'りっしゅう', 'Risshū', 'Start of autumn'],
  ['処暑', 'しょしょ', 'Shosho', 'Manageable heat'],
  ['白露', 'はくろ', 'Hakuro', 'White dew'],
  ['秋分', 'しゅうぶん', 'Shūbun', 'Autumn equinox'],
  ['寒露', 'かんろ', 'Kanro', 'Cold dew'],
  ['霜降', 'そうこう', 'Sōkō', 'Frost falls'],
  ['立冬', 'りっとう', 'Rittō', 'Start of winter'],
  ['小雪', 'しょうせつ', 'Shōsetsu', 'Lesser snow'],
  ['大雪', 'たいせつ', 'Taisetsu', 'Greater snow'],
  ['冬至', 'とうじ', 'Tōji', 'Winter solstice'],
  ['小寒', 'しょうかん', 'Shōkan', 'Lesser cold'],
  ['大寒', 'だいかん', 'Daikan', 'Greater cold'],
];

// 72 kō, starting at 立春 (315°), every 5°. [kanji, romaji reading, English]
export const KO = [
  ['東風解凍', 'Harukaze kōri o toku', 'East wind melts the ice'],
  ['黄鶯睍睆', 'Kōō kenkan su', 'Bush warblers start singing'],
  ['魚上氷', 'Uo kōri o izuru', 'Fish emerge from the ice'],
  ['土脉潤起', 'Tsuchi no shō uruoi okoru', 'Rain moistens the soil'],
  ['霞始靆', 'Kasumi hajimete tanabiku', 'Mist starts to linger'],
  ['草木萌動', 'Sōmoku mebae izuru', 'Grass sprouts, trees bud'],
  ['蟄虫啓戸', 'Sugomori mushito o hiraku', 'Hibernating insects surface'],
  ['桃始笑', 'Momo hajimete saku', 'First peach blossoms'],
  ['菜虫化蝶', 'Namushi chō to naru', 'Caterpillars become butterflies'],
  ['雀始巣', 'Suzume hajimete sukuu', 'Sparrows start to nest'],
  ['櫻始開', 'Sakura hajimete saku', 'First cherry blossoms'],
  ['雷乃発声', 'Kaminari sunawachi koe o hassu', 'Distant thunder'],
  ['玄鳥至', 'Tsubame kitaru', 'Swallows return'],
  ['鴻雁北', 'Kōgan kaeru', 'Wild geese fly north'],
  ['虹始見', 'Niji hajimete arawaru', 'First rainbows'],
  ['葭始生', 'Ashi hajimete shōzu', 'First reeds sprout'],
  ['霜止出苗', 'Shimo yamite nae izuru', 'Last frost, rice seedlings grow'],
  ['牡丹華', 'Botan hana saku', 'Peonies bloom'],
  ['蛙始鳴', 'Kawazu hajimete naku', 'Frogs start singing'],
  ['蚯蚓出', 'Mimizu izuru', 'Worms surface'],
  ['竹笋生', 'Takenoko shōzu', 'Bamboo shoots sprout'],
  ['蚕起食桑', 'Kaiko okite kuwa o hamu', 'Silkworms start feasting on mulberry leaves'],
  ['紅花栄', 'Benibana sakau', 'Safflowers bloom'],
  ['麦秋至', 'Mugi no toki itaru', 'Wheat ripens'],
  ['蟷螂生', 'Kamakiri shōzu', 'Praying mantises hatch'],
  ['腐草為螢', 'Kusaretaru kusa hotaru to naru', 'Rotten grass becomes fireflies'],
  ['梅子黄', 'Ume no mi kibamu', 'Plums turn yellow'],
  ['乃東枯', 'Natsukarekusa karuru', 'Self-heal withers'],
  ['菖蒲華', 'Ayame hana saku', 'Irises bloom'],
  ['半夏生', 'Hange shōzu', 'Crow-dipper sprouts'],
  ['温風至', 'Atsukaze itaru', 'Warm winds blow'],
  ['蓮始開', 'Hasu hajimete hiraku', 'First lotus blossoms'],
  ['鷹乃学習', 'Taka sunawachi waza o narau', 'Hawks learn to fly'],
  ['桐始結花', 'Kiri hajimete hana o musubu', 'Paulownia trees produce seeds'],
  ['土潤溽暑', 'Tsuchi uruōte mushi atsushi', 'Earth is damp, air is humid'],
  ['大雨時行', 'Taiu tokidoki furu', 'Great rains sometimes fall'],
  ['涼風至', 'Suzukaze itaru', 'Cool winds blow'],
  ['寒蝉鳴', 'Higurashi naku', 'Evening cicadas sing'],
  ['蒙霧升降', 'Fukaki kiri matō', 'Thick fog descends'],
  ['綿柎開', 'Wata no hana shibe hiraku', 'Cotton flowers bloom'],
  ['天地始粛', 'Tenchi hajimete samushi', 'Heat starts to die down'],
  ['禾乃登', 'Kokumono sunawachi minoru', 'Rice ripens'],
  ['草露白', 'Kusa no tsuyu shiroshi', 'Dew glistens white on grass'],
  ['鶺鴒鳴', 'Sekirei naku', 'Wagtails sing'],
  ['玄鳥去', 'Tsubame saru', 'Swallows leave'],
  ['雷乃収声', 'Kaminari sunawachi koe o osamu', 'Thunder ceases'],
  ['蟄虫坏戸', 'Mushi kakurete to o fusagu', 'Insects hole up underground'],
  ['水始涸', 'Mizu hajimete karuru', 'Farmers drain the fields'],
  ['鴻雁来', 'Kōgan kitaru', 'Wild geese return'],
  ['菊花開', 'Kiku no hana hiraku', 'Chrysanthemums bloom'],
  ['蟋蟀在戸', 'Kirigirisu to ni ari', 'Crickets chirp around the door'],
  ['霜始降', 'Shimo hajimete furu', 'First frost'],
  ['霎時施', 'Kosame tokidoki furu', 'Light rains sometimes fall'],
  ['楓蔦黄', 'Momiji tsuta kibamu', 'Maple leaves and ivy turn yellow'],
  ['山茶始開', 'Tsubaki hajimete hiraku', 'Camellias bloom'],
  ['地始凍', 'Chi hajimete kōru', 'Land starts to freeze'],
  ['金盞香', 'Kinsenka saku', 'Daffodils bloom'],
  ['虹蔵不見', 'Niji kakurete miezu', 'Rainbows hide'],
  ['朔風払葉', 'Kitakaze konoha o harau', 'North wind blows the leaves from the trees'],
  ['橘始黄', 'Tachibana hajimete kibamu', 'Tachibana citrus turns yellow'],
  ['閉塞成冬', 'Sora samuku fuyu to naru', 'Cold sets in, winter begins'],
  ['熊蟄穴', 'Kuma ana ni komoru', 'Bears start hibernating'],
  ['鱖魚群', 'Sake no uo muragaru', 'Salmon gather and swim upstream'],
  ['乃東生', 'Natsukarekusa shōzu', 'Self-heal sprouts'],
  ['麋角解', 'Sawashika no tsuno otsuru', 'Deer shed antlers'],
  ['雪下出麦', 'Yuki watarite mugi nobiru', 'Wheat sprouts under the snow'],
  ['芹乃栄', 'Seri sunawachi sakau', 'Parsley flourishes'],
  ['水泉動', 'Shimizu atataka o fukumu', 'Springs thaw'],
  ['雉始雊', 'Kiji hajimete naku', 'Pheasants start to call'],
  ['款冬華', 'Fuki no hana saku', 'Butterburs bud'],
  ['水沢腹堅', 'Sawamizu kōri tsumeru', 'Ice thickens on streams'],
  ['鶏始乳', 'Niwatori hajimete toya ni tsuku', 'Hens start laying eggs'],
];

export const koIndex = (sunLon) => Math.floor((((sunLon - 315) % 360) + 360) % 360 / 5);
export const sekkiIndex = (sunLon) => Math.floor((((sunLon - 315) % 360) + 360) % 360 / 15);

// Word of the week — journaling / season vocabulary, one per week (14 weeks).
// [kanji, kana, romaji, meaning]
export const WORDS = [
  ['日記', 'にっき', 'nikki', 'diary'],
  ['月見', 'つきみ', 'tsukimi', 'moon-viewing'],
  ['紅葉', 'こうよう', 'kōyō', 'autumn leaves'],
  ['記録', 'きろく', 'kiroku', 'record, log'],
  ['静か', 'しずか', 'shizuka', 'quiet, calm'],
  ['休む', 'やすむ', 'yasumu', 'to rest'],
  ['星', 'ほし', 'hoshi', 'star'],
  ['霜', 'しも', 'shimo', 'frost'],
  ['感謝', 'かんしゃ', 'kansha', 'gratitude'],
  ['友達', 'ともだち', 'tomodachi', 'friend'],
  ['雪', 'ゆき', 'yuki', 'snow'],
  ['夜明け', 'よあけ', 'yoake', 'dawn'],
  ['冬至', 'とうじ', 'tōji', 'winter solstice'],
  ['振り返り', 'ふりかえり', 'furikaeri', 'looking back, reflection'],
];
