// Pioneer of the week: women and LGBTQ+ people in computing, science and sound.
// Checked against each person's Wikipedia article, Sept 2026. [name, years, what they did, useless-knowledge fact]
export const PIONEERS = [
  ['Ada Lovelace', '1815–1852', 'Her 1843 “Note G” on Babbage’s Analytical Engine is often called the first published computer program. She saw machines could handle music and symbols, not just numbers.', 'At 12 she designed wings from paper, oilsilk, wire and feathers and planned a book called “Flyology.”'],
  ['Alan Turing', '1912–1954', 'Defined the “universal machine” in 1936, led the Bletchley Park bombe work against Enigma, and proposed the Turing test in 1950. Prosecuted in 1952 for being gay; pardoned in 2013, and on the £50 note since 2021.', 'In hay fever season he cycled to Bletchley wearing a gas mask to keep the pollen out.'],
  ['Katherine Johnson', '1918–2020', 'NASA mathematician who computed trajectories for Alan Shepard’s 1961 flight. John Glenn refused to fly in 1962 until she checked the computer’s numbers. Presidential Medal of Freedom, 2015.', 'She started high school at 10 and graduated college at 18.'],
  ['Margaret Hamilton', 'b. 1936', 'Led the MIT team that wrote the Apollo flight software, and coined “software engineering.” Her priority system kept Apollo 11’s landing going through the 1202 alarms.', 'LEGO made her a minifigure next to her famous stack of code printouts as tall as she was.'],
  ['Sophie Wilson', 'b. 1957', 'Wrote BBC BASIC and designed the ARM instruction set in 1983 with Steve Furber. ARM chips now run nearly every smartphone. She transitioned in 1994.', 'She debugged the BBC Micro prototype while watching the 1981 royal wedding on a tiny portable TV.'],
  ['Hedy Lamarr', '1914–2000', 'Hollywood star who co-invented frequency hopping with composer George Antheil (patent 1942), inspired by synchronized player-piano rolls. The idea is an ancestor of Wi-Fi and Bluetooth.', 'An asteroid, 32730 Lamarr, is named after her. Born Nov 9 — next Monday.'],
  ['Wendy Carlos', 'b. 1939', 'Her 1968 album Switched-On Bach made the Moog synthesizer famous and won three Grammys. Scored A Clockwork Orange, The Shining and Tron. She came out publicly as trans in 1979.', 'She is also a serious solar-eclipse photographer, published by NASA and Sky & Telescope. Born Nov 14 — this Saturday.'],
  ['Sally Ride', '1951–2012', 'First American woman in space, on STS-7 in 1983, and at 32 the youngest American astronaut to fly. She ran the shuttle’s robotic arm. Her obituary named her partner of 27 years, Tam O’Shaughnessy, making her the first astronaut known to be LGBTQ.', 'She was a ranked junior tennis player before physics won.'],
  ['Audrey Tang', 'b. 1981', 'Civic hacker from the g0v movement who became Taiwan’s first Digital Minister and first transgender cabinet member. Known for radical transparency and “humour over rumour.”', 'Started programming at 8, on paper, before having a computer.'],
  ['Annie Easley', '1933–2011', 'Worked 34 years at NASA Lewis (Glenn), from human computer to programmer. Wrote software for the Centaur rocket stage and did battery and energy research, and mentored as an EEO counselor.', 'A crater on the Moon was named Easley in 2021.'],
  ['Grace Hopper', '1906–1992', 'Navy rear admiral who built one of the first compilers (A-0) and shaped COBOL. She believed programs should read like English. Born Dec 9 — this week.', 'She handed out 11.8-inch wires: the distance light travels in one nanosecond. The 1947 moth “bug” is still taped in the Mark II logbook.'],
  ['Radia Perlman', 'b. 1951', 'Invented the Spanning Tree Protocol, which lets networks heal around broken links. She dislikes being called “the Mother of the Internet.” Born Dec 18 — this week.', 'She wrote a poem about her algorithm, “Algorhyme,” a riff on Joyce Kilmer’s “Trees.”'],
  ['Frances Allen', '1932–2020', 'IBM compiler-optimization pioneer. First female IBM Fellow (1989) and the first woman to win the Turing Award (2006).', 'She joined IBM in 1957 just to pay off student loans, and stayed 45 years.'],
  ['Lynn Conway', '1938–2024', 'Invented dynamic instruction scheduling at IBM, then co-led the Mead–Conway VLSI revolution in chip design. IBM fired her in 1968 for transitioning and apologized in 2020. Born Jan 2 — this week.', 'As a kid she built her own 6-inch reflector telescope over one summer.'],
];
